oumpy/hp_management

- .gitmodules
- README.md
- init.sh
- pelicanconf.py
Some manual reset or remaking local repository may be necessary for this update.
> pelican-plugins added & LaTeX support (render_math) enabled. 

- content/pages/achievements.md
This may be the last commit of contents before website will be open.
> Add description of freesound

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
I'm preparing to unify our homepage and blog into Pelican. 
I made the Syntax highlight easier to see.
Best regards.
> Update Syntax highlight style

- theme/voidy-bootstrap/templates/includes/custom/sb_taglist.html
I fixed tag-list to list style.
> Fix sb_taglist.html

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
> Fix css of taglist

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
Reverts oumpy/hp_management#47
> Revert "Comment out css of  ipynb notebook cells"

- theme/voidy-bootstrap/templates/includes/custom/footer.html
Reverts oumpy/hp_management#76
> Revert "Add comment system with utteranc.es"

- pelicanconf.py
- theme/voidy-bootstrap/templates/includes/custom/utterances.html
I added the comment system on articles footer with utterances.
See: 
https://github.com/oumpy/hp_management/issues/73
> Add comment system with utteranc.es

- content/articles/2019sy/News/website_integration.md
- content/articles/2019sy/News/website_renewal.md
- content/articles/2019sy/Tech_archive/DABEST_tutorial.md
I fix News and solve https://github.com/oumpy/hp_management/issues/81.
> Fix some articles

- .github/CODEOWNERS
CODEOWERS file revised. After this is merged I will change the protection setting of master branch for it to take effect. Pull request & review by the code owners will be essential for master branch.
> CODEOWNERS revised.

- content/README.md
Some explanations added on making internal links.
> content/README.md: How to make internal links.

- content/README.md
Explanations about initial settings were revised & enriched.
> content/README.md : How to post

- content/articles/2018sy/Blog/julia_python_competition.md
minor corrections on metadata & tag of a 2018ay article.
> 「JuliaとPythonと競技プログラミング」minor corrections.

- content/articles/2018sy/Blog/sushi_typing.md
- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
https://github.com/oumpy/hp_management/issues/145
I added css code to make youtube iframe responsive, and fixed article which contains youtube.
> Responsive youtube iframe

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
https://github.com/oumpy/hp_management/issues/145
I add `!important` to max-width and height
> Responsive youtube #2

- pelicanconf.py
Additional work to #141, to support multiple authors in article lists.
> Apply multiple authors to article lists.

- .gitmodules
- tools/updatesite.sh
Exclusive lock system mentioned in #118 was implemented, to avoid errors in sequential merges in a short time.
> Lock in updatesite.sh

- tools/updatesite.sh
Sorry but there was a bug in #152. This is a fix for it.
> Bugfix for locking system.

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
I made images center to look well.
> Centering of images

- content/README.md
Revise how-to-post, mainly addition of Method 2 (= direct push on oumpy).
> content/README.md: Revise how-to-post.

- Makefile
- content/postprocess.sh
- tools/init.sh
- tools/init_output.sh
- tools/init_repository.sh
- tools/setcgi.sh
- tools/updatesite.sh
This is a technical improvement of tools/ scripts, which is necessary for the preview system.
> Improvements of tools/ scripts

- .github/workflows/delete_preview.yml
- .github/workflows/preview.yml
- content/contentconf.py
This is a preview system for general branches (except for master).
For example, when a branch `refs/heads/hogehoge` is pushed, the compiled site will be uploaded under oumpy.github.io/previews/refs/heads/hogehoge.
Please review this script after the deploy_on_site.yml turns to work well successfully.
> Preview System by GitHub Actions

- .github/workflows/deploy_on_site.yml
Suppression of errors when nothing to push, etc.
> Minor improvements of publish system

- theme/voidy-bootstrap/templates/base.html
This patch copies the original base.html from voidy-bootstrap (commit 1), add an potion HIDE_ARCHIVES (commit 2), and another option ADD_ON_MENU (commit 3).
These give you great freedom to customize the menu, adding & hiding almost arbitrary pages there.
> Make Menubar customizable

- .github/workflows/delete_preview.yml
- .github/workflows/preview.yml
Steps reordered, to minimize the time lag from pull to push, avoiding interferences between actions.
> minor improvements of preview system.

- .github/workflows/deploy_on_site.yml
I'm sorry but due to my carelessness, the previous patch #187 included some reverses for past changes. This patch fixes that.
> Publish system: Revert unexpected reverses.

- content/pages/includes/news_content.html
Very simple preamble for the News page, just referring to Twitter, was added.
> News preamble

- content/contentconf.py
- content/pages/includes/blog_content.html
- pelicanconf.py
- theme/voidy-bootstrap/templates/includes/custom/content_top_category.html
The tag-list should be written as TAG_GROUPS in contentconf. This automatically generates the list on blog.html
> Semi-auto generation of tag-group list on blog.html

- pelicanconf.py
This patch converts h2, h3,... to strong, rather than deleting. Furthermore, more general replacements are also possible by just setting a dictionary variable.
> Autosummary: keep title tags in summary as strong

- content/contentconf.py
- theme/voidy-bootstrap/templates/includes/custom/sidebar.html
For GitHub, Email, YouTube, Twitter.
> Add services-specific icons to social links on sidebar.

- .github/labeler.yml
- .github/workflows/label.yml
It adds labels to PRs automatically, depending on the files changed.
> Auto-labeling system for pull-requests.

- content/pages/includes/blog_content.html
- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
It saves the space & make it easier to see the article list.
> Horizontal alignment for tag-group list.

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
Minor correction for appearance. Titlebar was felt to be too deep.
> Make titlebar a bit thinner, by 10px.

- .github/workflows/post_preview_link.yml
I hope it works.
Reference:
https://qiita.com/osakiy/items/df80db383ce33b82c797#comment-2fa1f29c729216bcfe39
> Post Preview-Links for every pull-request

- content/articles/2018sy/Blog/python_visualization.md
Fix errors created when it was converted from html, half-manually.
> Syntax-correct visualization.md (2018 article)

- content/create.py
In create.py, this patch makes `images/filename_figs/` for `filename.md`
> Add image-folder creation to content/create.py

- myplugins/autosummary/autosummary.py
There was a small bug in auto summary plugin and it could not process autogenerated long summaries. Due to that, some summaries are broken now. (I don't know since when they have been.)
This patch corrects it and also gives another minor technical correction.
> autosummary: Bugfix

- content/create.py
> Bugfix in content/create.py when a content markdown file is given.

- content/articles/2018sy/blog/breast_cancer_detection.md
> Add a hyperlink to 2018 article breast_cancer.md

- content/contentconf.py
- content/pages/search.md
- pelicanconf.py
- theme/voidy-bootstrap/templates/includes/custom/sb_google_cse.html
This patch adds a search box at the top of sidebar, and search.html where the search results are displayed, as an implementation for the issue #54.
Pull requests #253 & #258 must be merged before this patch.
> Add Google Custom Search Engine

- content/contentpublishconf.py
Tuning for the Google search, etc.
> Sitemap: reduce the weight for index pages.

- content/articles/2020sy/blog/studymeeting2020_01.md
- content/articles/2020sy/blog/studymeeting2020_02.md
- theme/voidy-bootstrap/templates/includes/custom/open_in_colab_scripts.html
studymeeting2020_01.md is also corrected.
> Add badge of colab link to attached ipynb files, rather than replacing URL.

- content/articles/2020sy/blog/neural_tangents.ipynb
> Fix "neural_tangents" article

- pelicanconf.py
> Enable hyperlinks to tags/authors list in articles lists

- myplugins/apply_jinja2.py
This patch is an improvement of the plugin `apply_jinja2`. Merge it BEFORE the formal name announce.
> apply_jinja2: Update to apply Jinja2 to titles.

- theme/voidy-bootstrap/templates/base.html
This patch should also be merged before the formalname_all.
> base.html: Add striptags to SITENAME.

- content/contentconf.py
Just a minor correction of `contentconf.py`, deleting old & invalid settings.
> Delete invalid settings of AUTHOR properties.

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
I added a blockquote style. This looks like the following picture.
> Add blockquote style

- theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
I deleted some spaces of articles converted from jupiter notebooks by adjusting CSS. 
https://github.com/oumpy/hp_management/issues/335
> Appearance of Jupyter Notebooks

- content/pages/about.md
Just a technical correction, to erase warning.
> Correct {filename} to {static} in about.md

- content/contentconf.py
- pelicanconf.py
- theme/voidy-bootstrap/templates/includes/custom/sb_donate.html
- theme/voidy-bootstrap/templates/includes/custom/sb_support.html
This patch adds a sidebar-box "Support to the Party", including PayPal.Me link.
> Add PayPal.Me Link to the Sidebar

- content/articles/2019sy/blog/shellscript_tutorial.md
I found that this article is mainly on basic Unix commands, rather than shell scripts.
> shellscript_tutorial.md: Add tag 'Unix'.

- content/contentconf.py
@takyamamoto You should include this by yourself in your article PR, or make a separate PR if necessary, whenever you would like to put a new tag.
> Rename 'Research tools & techniques' to 'Research tools & topics'.

- myplugins/autosummary/autosummary.py
This PR updates the autosummary plugin.
By default, it excludes < h1 > tags from generated summary, especially in jupyter notebooks.
For example, you can see how it works, in the summaries of the IRMAE & blood-sugar articles on the articles list.
> autosummary: Add `AUTOSUMMARY_DELETE_HTMLTAGS`

- content/articles/2019sy/blog/exam_vs_python.md
- content/contentconf.py
Upload one of old articles, together with a new tag, '勉学支援'.
> Add 2019 article, '試験 vs Python'.

- content/articles/2018sy/blog/TCGAbiolinks.md
> Add 2018 article as TCGAbiolinks.md, "TCGAbiolinksとその使い方".

- content/articles/2020sy/blog/attention.md
> 勉強会資料2021年3月

- content/create.py
This PR corrects some bugs of `create.py`, and also corrects the problem that `~/` did not work in the path for content file.
> Debug & Improvement of content/create.py

- content/contentconf.py
#396 includes this tag. It is desirable to merge this PR almost at the same time as #396 but it is not essential.
> contentconf: Add a new tag, 'その他言語' in Programming section.

- content/pages/achievements.md
Emergence of Yellow Coder, and minor update.
> achievements.md: Update on AtCoder

- content/articles/2021sy/blog/seti.md
> modift Author,add <br>

- content/pages/student_server.md
Reflect the new Alice specs after the upgrade in 2021 Sep.
> Student server: update the specs.

- content/pages/student_server.md
> student_server.md: Update modified date.

- content/articles/2021sy/blog/kaggle_advent_2021_18.md
> kaggle advent_2021

- .github/workflows/delete_preview.yml
It's already working perfectly, and this is a very minor correction.
> delete_preview.yml: minor correction on commit comment.

- .github/workflows/preview.yml
This PR corrects conflicts between different previews or previews and master branch.
> preview.yml: Update to avoid conflicts with other actions.

- .github/workflows/delete_preview.yml
- .github/workflows/deploy_on_site.yml
- .github/workflows/preview.yml
It is a minor update and you do not need to hurry up to merge it.
> Update action setup-python v1->v2, in github actions workflows

- content/articles/2021sy/blog/cytology.md
- content/pages/achievements.md
甲状腺細胞診が雑誌に載ったことを追記、実績にも追記。実績に安部のインターンを追加、実績に2020年度自主研究を追加
> 実績とcytologyの更新

- content/articles/2021sy/blog/Kaggle Tabular Playground Series - Dec 2021.md
石本樹生です。12月のKaggleのコンペの記事を作成しました。
> Kaggle Tabular Playground Series - Dec 2021.md

- .github/workflows/delete_preview.yml
$REF -> branch name, in the commit message of GitHub Pages.
> workflows/delete_preview.yml: Correct commit message.

- content/articles/2022sy/blog/NonAbelian_1loop.nbdata
`NonAbelian_1loop.nbdata`を追加しました
> Added NonAbelian_1loop.nbdata

- .github/workflows/delete_preview.yml
- .github/workflows/deploy_on_site.yml
- .github/workflows/preview.yml
This is a rescue PR for an error in Python 3.12 in some plugins.
This must be merged as soon as possible, before any other PR.
(We should correct the corresponding plugins issues & revert this PR later.)
> [Urgent] Fix Python 3.11 temporarily, to avoid deprecation of distutils in 3.12.

- content/pages/achievements.md
> achievements.md: Correct a syntax bug.

- content/pages/achievements.md
- content/pages/student_server.md
A member's paper published in 2023 January.
> Add a paper by Ogawa, in achievements.md & student_server.md

- .github/workflows/deploy_on_site.yml
- .github/workflows/preview.yml
This PR corrects a bug of auto-reflection system from the source to the website.
> workflows: correct wrong corrections of set-output.

- content/contentconf.py
- theme/voidy-bootstrap/templates/includes/custom/footer.html
E.g., "© 2025 大阪大学医学部Python会" -> "©2018-2025 大阪大学医学部Python会"
Please review it, and JUST APPROVE WITHOUT MERGING.
> Add Copyright year "2018-".
