pelicanconf.py
Correct the height of twitter timeline 720, which was too long.
=> shorten the height of twitter timeline.

theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
CSS for tables. Without it some articles are not somewhat beautiful.
=> CSS for tables, copied from github theme of Typora.

Makefile, content/postprocess.sh, pelicanconf.py
Currently the URLs of articles are like
oumpy.github.io/articles/yyyy/mm/name.html,
regardless it is News or Blog.
This patch changes it like
oumpy.github.io/blog/yyyy/mm/name.html,
and for blog articles, make symbolic links and the same article can also be accessed via
oumpy.github.io/articles/yyyy/mm/name.html,
so that the already-announced links on Twitter would not be killed.
=> Article URL change

content/pages/achievements.md, content/pages/activities.md, content/pages/recruit.md, pelicanconf.py, theme/voidy-bootstrap/static/css/voidybootstrap-custom.css, theme/voidy-bootstrap/templates/includes/custom/header_page.html, theme/voidy-bootstrap/templates/includes/custom/page_showmodified_scripts.html
By adding "Show_modified: True" to the metadata of a page, modified date for the page is shown at lower-right of the title.
recruit, activities, achievements are set for this.
=> Show modified dates on selected pages

pelicanconf.py
This patch enables inclusion of YouTube videos in pages & articles, by writing
{% youtube youtube_id [width] [height] %}
in markdown sources.
[width] & [height] can be omitted.
=> load plugin liquid_tags.youtube

content/pages/recruit.md, pelicanconf.py
Introduction video added to recruit.md, by using liquid_tags plugin. It is better to process this pull request after #129 has been merged.
=> Add video on recruit page.

content/articles/2019sy/Blog/atcoder_beginners_selection.md
Because the original filename was too general and not good as an example.
=> 2019 article atcoder.md renamed to atcoder_beginners_selection.md

theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
I centered all images, but didn't want to do that for the images of open in GitHub / colab, so I added the css code.
Please check
=> Do not make center images of open in github / colab 

requirements.txt
nbconvert does not depend on IPython. pelican-ipynb plugin depends on both.
=> Bugfix: add IPython in requirements.txt

.github/docker/Dockerfile, .github/workflows/deploy_on_site.yml
This is a childish implementation of #149. Instead of the present external server, it runs compiling & publishing on a Docker container provided by GitHub Actions. It closes everything within GitHub.
I DON'T KNOW whether it works, largely because I'm very new to GitHub Actions. However I think it is harmless even if it doesn't work.
I temporally stopped the webhook trigger to the external server (set dummy.cgi, rather than the correct deploy.cgi). After some checks which you can, please try.
=> Auto-publish system replaced by GitHub Actions

.github/workflows/deploy_on_site.yml
Correct username for GitHub in SSH authentication. (It MUST be 'git'.)
I expect this patch will solve the problem #170 in #149 .
=> Correct SSH configuration in GitHub Actions Auto-publish System

.github/workflows/deploy_on_site.yml
"Suppression of errors when nothing to push" in #184 was not actually included. This is a correction, very small patch.
(now by the randomness in tag_cloud, this does not have effects in fact.)
=> minor error correction in publish system

pelicanconf.py, theme/voidy-bootstrap/templates/includes/custom/index_summary.html, theme/voidy-bootstrap/templates/includes/index_summaries.html
This is the first implementation for issue #155 .
For articles without summary, this system generates the summary automatically, by taking twitter-long part of the beginning of the article, keeping some selected html tags (a, font, etc) & deleting others.
You can see from the preview that it fairly improves the view of the blog page, and I think it motivates the readers to read the articles.
Unfortunately for jupiter notebooks it outputs nonsense headers, but I don't think it is not a critical problem, and fixable later if necessary.
=> Auto-Summary System for articles

content/contentconf.py, theme/voidy-bootstrap/templates/category.html, theme/voidy-bootstrap/templates/includes/custom/article_header_info.html, theme/voidy-bootstrap/templates/includes/custom/content_top_category.html, theme/voidy-bootstrap/templates/includes/custom/sidebar.html
This patch enables a new option CUSTOM_CATEGORY_NAMES, which is set in contentconf.py as
{'Blog': '技術ブログ', 'News': 'お知らせ'}。Alternative names are shown instead of the internal category name, everywhere in the website.
=> Alternative Japanese name for categories

content/articles/2020sy/Blog/neural_tangents.ipynb
I found a small typo. 
NKT -> NTK
=> Fix typo in neural_tangents.ipynb

content/contentpublishconf.py, publishconf.py
By using sitemap plugin, sitemap.xml is added to the site, for crawlers of google, etc. 
Note that this works only for `make publish`, so does nothing in the preview.
=> Sitemap.xml added

theme/voidy-bootstrap/templates/includes/custom/article_header.html, theme/voidy-bootstrap/templates/includes/custom/article_header_info.html
It saves spaces & increases number of articles you can see on the list at the same time.
=> Move article dates, from above title to below title

myplugins/autosummary/autosummary.py
There was a small bug. When summary ends in `<h2>...</h2>` for example, it did not close the replaced `<strong>` correctly. It was something like typo, and it has now been corrected.
=> autosummary: small bugfix

content/contentpublishconf.py
Very minor small correction.
Along with the official recommendation, put https://.
=> Put https:// at the head of SITEURL.

content/contentconf.py
'darkreen' -> 'darkgreen'.
Thanks to the clever correction by shields.io, it did not affect the appearance of the site.
=> correct typo

content/contentconf.py
Before the correction #214, 'darkreen' seems to have been interpreted as 'green' rather than 'darkgreen'. I don't know why but anyway the present darkgreen looks too dark. 'green' looks better.
=> badge color 'darkgreen' -> 'green'

theme/voidy-bootstrap/templates/includes/custom/sidebar.html
This patch is for an old issue #53. On the preview, make the window narrower, and you will see what happens. This two-column feature is not applied on many mobile devices ('xs' window width of bootstrap).
=> two-column view on sidebar, for narrower window

content/contentconf.py, theme/voidy-bootstrap/templates/includes/custom/footer.html
Parameters COPYRIGHT_YEAR & COPYRIGHT_AUTHOR are set in contentconf.py
The appearance is totally unchanged.
You don't have to update the theme every year. The year is now set automatically by Python, at every update of master branch.
=> Move copyright information from theme to content/contentconf

.github/workflows/delete_preview.yml
In the preview system, there was a bug that previews are not deleted when the branch is deleted. This must be a problem of git staging, although I do not know the precise reason of that yet.
Anyway this patch is a more rigid way to do it.
=> Delete_Preview: Fix of non-delete bug.

theme/voidy-bootstrap/templates/page.html
'A page in' appears when the pages are linked, which is ugly. Delete it.
=> Delete 'A Page in' from the default description of pages

content/pages/recruit.md, pelicanconf.py
All 8 presentation movies added.
At the same time, the plugin `liquid_tags` was replaced by `shortcodes` and a simple setting in pelicanconf.py, for YouTube movies.
=> recruit.md: Add recruit presentation movies.

.github/workflows/deploy_on_site.yml
This is a countermeasure against collisions between sequential merges, which happened in the previous update.
=> Revise deploy_on_site.yml, to avoid collisions among sequential merges.

content/contentconf.py, pelicanconf.py
This patch enables on to use in contentconf the variables defined in pelicanconf.
For that purpose it added a dummy empty file tools/lib/pelicanns.py, than which I do not know a better method.
=> Improve connections between pelicanconf.py & contentconf.py

content/template.md, myplugins/filename2slug/LICENSE, myplugins/filename2slug/ReadMe.md, myplugins/filename2slug/__init__.py, myplugins/filename2slug/filename2slug.py, pelicanconf.py
Without `slug` metadata, this patch makes default slug from the filename.
=> Let slug metadata be omittable

myplugins/filename2slug/filename2slug.py
In #233 there was a critical bug that prefers filename than metadata as its slug. This changed index.html to about.html, deleting the very top-page of the site. This patch fixes it. Please approve & merge it as soon as possible.
=> [URGENT] filename2slug: critical bugfix

content/contentconf.py
Just turned on the built-in function of voidy-bootstrap theme.
=> Add article numbers to tag_cloud in the sidebar.

theme/voidy-bootstrap/templates/includes/custom/header_article.html, theme/voidy-bootstrap/templates/includes/custom/open_in_colab_scripts.html
Introduction of `category_name` plugin brought out a bug on on the colab-link. This patch corrects it and make the links alive again.
Note that this patch only works after merging #251.
=> Bugfix on colab-link to jupyter notebooks.

myplugins/apply_jinja2.py, pelicanconf.py, theme/voidy-bootstrap/templates/includes/custom/content_top_category.html
By setting `Jinja2: True` in metadata, this patch deals the article/page as a Jinja2 template, in which you can use almost all variables that are provided for theme templates.
This PR should be reviewed after #253 is successfully merged.
=> Enable to deal articles/pages as Jinja2 templates

.github/workflows/preview.yml
In order to work when `SITEURL` is not `.`.
=> preview.yml: very minor correction.

myplugins/filename2slug/filename2slug.py
This patch corrects `filename2slug`, so that the default slugs are given at an earlier stage of compile. That erases potential errors in interferences with other plugins.
=> Fix plugin filename2slug

Makefile, content/contentconf.py, myplugins/postprocess.py
So far, postprocessing script `content/postprocess.sh` (making symbolic links) was called from Makefile. This patch introduces a new simple plugin `postprocess`, which can call arbitrary postprocessing script by a very simple configuration. In a setting in contentconf, it calls `postprocess.sh`.
=> Move postprocess from Makefile to Plugin

myplugins/subsections/LICENSE, myplugins/subsections/ReadMe.md, myplugins/subsections/__init__.py, myplugins/subsections/subsections.py
This plugin adds an attribute `subsections` to every page & article. It includes all the tree structure of the sections in the document. At the same time it inserts `id="...."` to each section, whose information is also stored in `subsections`.
In this patch it is not added to `PLUGINS`.
=> Add a plugin `subsections`

pelicanconf.py
Since the order is now set manually in contentconf.py, `page_order` setting is no longer necessary.
=> pelicanconf: Comment out `PAGE_ORDER_BY = 'page_order'`

myplugins/path2obj/LICENSE, myplugins/path2obj/ReadMe.md, myplugins/path2obj/__init__.py, myplugins/path2obj/path2obj.py
This plugin provides two filters `source2obj` & `url2obj`, which converts source paths or generated file paths (=URL) to the objects.
This patch just adds the plugin, not adding it to `PLUGINS`.
=> Add plugin `path2obj` : provide filters `source2obj` & `url2obj`

content/contentconf.py, myplugins/makemenu.py, pelicanconf.py, theme/voidy-bootstrap/templates/base.html
This patch imports only some part of #237, including the `makemenu` plugin.
It does NOT introduce advanced multi-hierarchal menu. The appearance will not be changed almost at all.
The major merit is that the menu items are more appropriately highlighted. Currently, the menu '技術ブログ' is not highlighted for individual blog articles. Similar for individual news. The high customizability of the `makemenu` plugin resolves the problem.
The remaining part of the advanced menu system will be still left in #237. The appearance problem of multi-hierarchal menu is not resolved yet there.
=> Use `makemenu` for menubar, activating articles correctly.

.github/workflows/preview.yml
Internal links are not working for previews, due to a kind of typo.
=> Bugfix on internal links in previews.

theme/voidy-bootstrap/templates/base.html
In 2nd, 3rd,... pages of article lists, the menu link of blog is dead. This patch fixes the bug.
=> Bugfix on menu-link in paginated lists.

theme/voidy-bootstrap/templates/includes/custom/scrolltop_scripts.html
=> scrolltop_scripts: minor correction.

content/pages/about.md, content/pages/achievements.md, content/pages/activities.md, content/pages/constitution.md, content/pages/contact.md, content/pages/recruit.md, content/pages/search.md
This patch deletes metadata `author` & `page_order` in pages, which are not used and not necessary.
=> Delete unnecessary metadata from pages

theme/voidy-bootstrap/templates/includes/custom/sb_social.html
Feed links were dead in deeper pages, such as articles. This patch corrects it in a rather ad-hoc way. It may not be the best but it works.
=> Debug of the breakdown of sb_social feed links in deeper pages

.github/workflows/preview.yml, .github/workflows/webhook_delete_artifacts.yml
This patch prevents wasting disk spaces in GitHub. 
Before this patch, merge #181.
#181 is already tested on its own branch. This patch should be in master branch to work, then it has not been tested, although it should work since it is almost a copy & paste from the readme of the action.
=> Delete intermediate files in preview system

myplugins/skiptags.py, pelicanconf.py
This patch is another attempt for #335 , to delete the title of the original notebook title.
=> Add new plugin SkipTags, to delete h1 from JupyerNotebooks.

myplugins/skiptags.py
The SkipTags includes a critical bug which fails in building, because of a conflict to SiteMap plugin which is called only in `make publish`, which I did not notice in my test by `make html`.
This patch corrects it, and should be applied URGENTLY.
=> SkipTags: Correct CRITICAL Error.

content/contentpublishconf.py
In Google searches, it seems that the indexing is not working in a nice manner. I'm not very sure on the cause but anyway the pages should have larger weight than articles in general.
=> Sitemap: Make weight larger for pages.

myplugins/skiptags.py
Due to a complicated interference between plugins, the Google Customized Search Engine has been dead. This patch is a bugfix for it. Please merge it as soon as possible.
=> Bugfix: Restore the Google search engine.

pelicanconf.py, publishconf.py, requirements.txt
This PR also includes update of nbconvert, to which Pelican & plugins are now compatible.
=> Update some plugins to newer-style (Pelican >= 4.5)

pelicanconf.py, requirements.txt
This PR prevents mis-executes of Jekyll on GitHub actions, and also makes the update-appearance faster (according to the plugin document).
=> Enable `nojekyll` plugin.

requirements.txt
Due to my own mistake, all of the jupyter-notebook articles are gone now. This PR corrects it by downgrading `nbconvert` to the compatible version.
Please merge it as soon as possible.
=> [Urgent] requirements.txt: Revert nbconvert version to 5.6.1

theme/voidy-bootstrap/static/css/voidybootstrap-custom.css
I modified the css for code blocks. The code block paddings are different between jupyter notebook input block and the raw markdown code block with the present css. So, I deleted the margin depending on jupyter notebook, and added the padding of code blocks. Both code blocks got similar looking.
Before:
After :
=> Modified CSS for code block padding 

.github/workflows/delete_preview.yml
This PR corrects the long-standing bug, #228, enabling to delete previews automatically, when the corresponding PR brunches are deleted.
=> Correct delete_preview.yml, for the issue #228.

.github/workflows/deploy_on_site.yml, Makefile
This PR corrects a known problem that sequential pushes (including adding/deleting branches) conflict with each other and some changes are lost, especially around previews.
Similar but larger corrections are made in `preview.yml` in another, sister PR.
=> deploy_on_site.yml: Update to avoid conflicts with other actions.

requirements.txt
Fix Jinja2==3.03, which deletes the error.
THIS SHOULD NOT BE PERMANENT.
Maybe Pelican updates will correct the error, or maybe we should carry-out some fundamental fix.
The cause of the error is simple. As in https://jinja.palletsprojects.com/en/3.0.x/api/, `contextfilter()` has been deleted from Jinja2 (>=3.1.0) and we must use `pass_context()`.
=> Temporary-aid for jinja2 error in builds.

.github/workflows/delete_preview.yml, .github/workflows/deploy_on_site.yml, .github/workflows/label.yml, .github/workflows/preview.yml
Now node16 is deprecated, and the auto-update system of this site is not working. 
This PR corrects it, by updating the actions to use node20.
=> Update versions of actions in workflows, to use node20.

pelicanconf.py
Up to now, the tag-list in the sidebar is ordered randomly every time. This PR deforms it such that the tags are sorted by the number of articles, descendingly.
=> tag_cloud: Change sorting, random -> size.

.github/workflows/delete_preview.yml, .github/workflows/deploy_on_site.yml, .github/workflows/preview.yml, requirements.txt
Now Pelican supports Python 3.13, with setuptools.
=> Update Python: 3.11 -> 3.13
